sudo: required
language: generic
services:
- docker
before_install:
- docker build -t $REPO .
after_success:
- docker --version
- docker tag $REPO $REPO:latest
- docker tag $REPO $REPO:git-$COMMIT
- docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
- docker push $REPO
env:
  global:
  - COMMIT=${TRAVIS_COMMIT::7}
  - secure: Y0cO9I8XGG0ZhPWrdAE+z+G/kSueaNt92sn34ULGWJEPerO5EEefjLNeQ+PMZpjXDupEw0mrgWjWAFRzxeijXIOiRtmBdh/TjIyFEFbgzV4Vy6Nqme8NMN+elNm3OEFZoofEZraNwJAee70udOA6tRlpGybwJ1gpRYv7Gj9jfJrW85cR28NL1TIxcy6eIIqe6Ue+GR1CFW1B6GTUtoIb2YAaaoclFBBd/0wkkUM0Lqt9ne/AkUdcLeuaZx1lbAfu9G7u/E277gz8TBUUjVJ5s4aydJggNXuKDOCHx3F6xoZVoGffyvSIAsoyPh9Ry72gtWRuObF7HRqslXFvNzYkRHY0JFxnNbQfSombYgA4e7153ZXB9LX5/HuSZglY25HCEFem2fhzJ2tya/MJ6DVFCJ+oUV2zVI9+rnxCLoc3hh6Syt6lRjvOW6KzRiFoQpPPra+3ZkE9SAhbdJuYNjt+nmu/+vOsMhk0/BDEBXF8SzVMmahgRvAnSQGOn3sBHtZAguEpcUUa2j7xRR2hZPfI0k8D8G+etMKYssUInbn85NbNccSPzC2iI5MeI3Pg/RuBDggbcTCklD0HfvWVtQSndTcjqvBQHNbbN/qPPMXfcbWvvwrB5QIclt8xwuYiJ0rV4Z2KUnx5rrrmrJNI5h+gmrU1mao+W+bsx4aXKYQaOEA=
